### ISSUE TITLE
Setup Kanboard

### ISSUE THREAD

**Issue by Nuri1977** [Nuri1977/recipe-application#16]
### Setup Kanboard
We are two members: @Nuri1977  and @mugishasam123.
The link to our project is: https://github.com/Nuri1977/recipe-application/projects/1

**Comment by Deepakdanger** [comment]
Hi @Team, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 

## Required Changes ♻️
- [ ] Students should add the following columns to the board:

* To Do
* In Progress
* In Review
* Done
- Kindly add the `In Review` column
![Screenshot from 2022-05-16 14-36-55](https://user-images.githubusercontent.com/26767383/168562111-5a23bb23-34e2-4feb-9406-9ee11327168d.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @Nuri1977  and @mugishasam123 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
